const now = new Date();
const ts = (minsAgo) => new Date(now.getTime() - minsAgo * 60000).toISOString();

export const systemAlerts = [
  {
    id: 'api-1',
    type: 'api',
    severity: 'critical',
    title: 'High 5xx Rate: /api/v2/kyc/liveness-check',
    summary: '42% failure rate in last 30 min (vs 1.2% baseline). 1,840 customers impacted.',
    detectedAt: ts(28),
    endpoint: '/api/v2/kyc/liveness-check',
    currentErrorRate: 42.0,
    baselineErrorRate: 1.2,
    impactedCustomers: 1840,
    logs: [
      { timestamp: ts(2),  endpoint: '/api/v2/kyc/liveness-check', responseCode: 502, customerId: 'PTM_U_98234501', latencyMs: 12400 },
      { timestamp: ts(4),  endpoint: '/api/v2/kyc/liveness-check', responseCode: 504, customerId: 'PTM_U_98234622', latencyMs: 30000 },
      { timestamp: ts(5),  endpoint: '/api/v2/kyc/liveness-check', responseCode: 502, customerId: 'PTM_U_98234718', latencyMs: 15200 },
      { timestamp: ts(8),  endpoint: '/api/v2/kyc/liveness-check', responseCode: 500, customerId: 'PTM_U_98234890', latencyMs: 890 },
      { timestamp: ts(11), endpoint: '/api/v2/kyc/liveness-check', responseCode: 502, customerId: 'PTM_U_98235012', latencyMs: 11800 },
      { timestamp: ts(14), endpoint: '/api/v2/kyc/liveness-check', responseCode: 504, customerId: 'PTM_U_98235145', latencyMs: 30000 },
      { timestamp: ts(18), endpoint: '/api/v2/kyc/liveness-check', responseCode: 502, customerId: 'PTM_U_98235290', latencyMs: 14300 },
      { timestamp: ts(22), endpoint: '/api/v2/kyc/liveness-check', responseCode: 500, customerId: 'PTM_U_98235401', latencyMs: 1200 },
      { timestamp: ts(25), endpoint: '/api/v2/kyc/liveness-check', responseCode: 502, customerId: 'PTM_U_98235589', latencyMs: 13100 },
      { timestamp: ts(28), endpoint: '/api/v2/kyc/liveness-check', responseCode: 504, customerId: 'PTM_U_98235672', latencyMs: 30000 },
    ],
  },
  {
    id: 'api-2',
    type: 'api',
    severity: 'warning',
    title: 'Elevated Latency: /api/v2/bureau/credit-pull',
    summary: 'p95 latency spiked to 8.4s (vs 1.8s baseline). 620 requests queued.',
    detectedAt: ts(15),
    endpoint: '/api/v2/bureau/credit-pull',
    currentErrorRate: 6.8,
    baselineErrorRate: 0.5,
    impactedCustomers: 620,
    logs: [
      { timestamp: ts(1),  endpoint: '/api/v2/bureau/credit-pull', responseCode: 200, customerId: 'PTM_U_88120301', latencyMs: 9200 },
      { timestamp: ts(3),  endpoint: '/api/v2/bureau/credit-pull', responseCode: 504, customerId: 'PTM_U_88120415', latencyMs: 30000 },
      { timestamp: ts(5),  endpoint: '/api/v2/bureau/credit-pull', responseCode: 200, customerId: 'PTM_U_88120520', latencyMs: 8100 },
      { timestamp: ts(7),  endpoint: '/api/v2/bureau/credit-pull', responseCode: 200, customerId: 'PTM_U_88120688', latencyMs: 7400 },
      { timestamp: ts(9),  endpoint: '/api/v2/bureau/credit-pull', responseCode: 504, customerId: 'PTM_U_88120790', latencyMs: 30000 },
      { timestamp: ts(12), endpoint: '/api/v2/bureau/credit-pull', responseCode: 200, customerId: 'PTM_U_88120899', latencyMs: 8800 },
    ],
  },
  {
    id: 'funnel-1',
    type: 'funnel',
    severity: 'critical',
    title: 'Conversion Drop: BUREAU_CHECK → KYC_VALIDATION',
    summary: 'Stage conversion fell to 61.2% (from 89.4% an hour ago). Cascading drop downstream.',
    detectedAt: ts(38),
    stage: 'BUREAU_CHECK → KYC_VALIDATION',
    currentConversion: 61.2,
    previousConversion: 89.4,
    baselineConversion: 88.7,
    sinceDuration: '38 min',
    trend: [
      { time: '-60m', rate: 89.1 },
      { time: '-50m', rate: 88.7 },
      { time: '-40m', rate: 82.3 },
      { time: '-30m', rate: 71.5 },
      { time: '-20m', rate: 64.8 },
      { time: '-10m', rate: 62.1 },
      { time: 'now',  rate: 61.2 },
    ],
    downstreamImpact: [
      { stage: 'KYC_VALIDATION → LENDER_BRE', drop: '-18.2%' },
      { stage: 'LENDER_BRE → MANDATE_SETUP', drop: '-12.7%' },
      { stage: 'MANDATE_SETUP → ESIGN', drop: '-8.4%' },
    ],
  },
  {
    id: 'funnel-2',
    type: 'funnel',
    severity: 'warning',
    title: 'Conversion Drop: ESIGN → CREDIT_LINE_ACTIVATION',
    summary: 'Stage conversion at 78.1% (was 92.6% at start of hour). Investigating.',
    detectedAt: ts(22),
    stage: 'ESIGN → CREDIT_LINE_ACTIVATION',
    currentConversion: 78.1,
    previousConversion: 92.6,
    baselineConversion: 93.0,
    sinceDuration: '22 min',
    trend: [
      { time: '-60m', rate: 93.1 },
      { time: '-50m', rate: 92.8 },
      { time: '-40m', rate: 91.4 },
      { time: '-30m', rate: 86.2 },
      { time: '-20m', rate: 80.5 },
      { time: '-10m', rate: 78.9 },
      { time: 'now',  rate: 78.1 },
    ],
    downstreamImpact: [
      { stage: 'CREDIT_LINE_ACTIVATION → LEAD_CLOSED', drop: '-6.1%' },
    ],
  },
];

export const alertSummary = {
  total: systemAlerts.length,
  critical: systemAlerts.filter(a => a.severity === 'critical').length,
  warning: systemAlerts.filter(a => a.severity === 'warning').length,
  oldestMinutesAgo: 38,
};
